### ISSUE TITLE
Problem with tab

### ISSUE THREAD

**Issue by nickm324** [malnvenshorn/OctoPrint-WebcamTab#1]
After installing the plugin and enabling it the webcam does get removed from the control panel but no new tab is created. So basically it just completely removes the webcam altogether from the UI.

**Comment by malnvenshorn** [comment]
I need more information to help:

* Have you tried to clear your browser cache?
* Have you tried this with all other 3rd party plugins disabled?
* What browser are you using?
* Are there any error in the javascript console of your browser?

**Comment by GaryBoone** [comment]
I found that the webcam did not move to a tab, but appeared as a new menu item in the dropdown menu on the right side of the tabs. 

So OP appears correct. It's not a tab, but a menu item. Is there a way to make it a tab? If not, it should be renamed "WebcamMenu."

[Chrome 63.0.3239.132; MacOS 10.13.2; Octoprint 1.3.6 on RPi3/Octopi]

**Comment by GaryBoone** [comment]
BTW, you might consider posting a screenshot on https://plugins.octoprint.org/plugins/webcamtab/ to show what it looks like when installed.

**Comment by malnvenshorn** [comment]
> So OP appears correct. It's not a tab, but a menu item. Is there a way to make it a tab? If not, it should be renamed "WebcamMenu."

It's still a tab, because of the limited space tabs get grouped into that menu if necessary. You can modify the tab order in the `config.yaml`. See the OctoPrint documentation for that.

**Comment by nickm324** [comment]
I looked in the Menu and it was not there. I have another plugin MultiColor and it gets moved to that menu also, but after enabling the WebCam Tab its not in the menu just the MultiColor plugin is listed. Anything I can check to troubleshoot this?

**Comment by nickm324** [comment]
I would post a screenshot if there was anything to take a screen shot of, after installing and enabling the plugin the only thing that changes is the webcam in the Control tab gets completely removed but thats it there is no other trace of the WebCam anywhere in OctoPrint after that.

**Comment by nickm324** [comment]
Well I uninstalled and reinstalled it and it worked this time. Unfortunately it doesn't really provide any benefit to the UI. I was under the assumption that the purpose to moving it to its own TAB(menu) was to make it larger (full page) but that wasn't the case. It simply moved it and it also didn't work with the Full Screen plugin that I had enabled which did work with the webcam when it was in the control tab. Maybe that's a feature request to make it full page after it gets put in its own tab.

**Comment by GaryBoone** [comment]
Reordering the tabs so the Webcam tab appears in the tabs, not the extra menu:

[1. edit octoprint's config.yaml. For my RPi installation, the sequence was:
  $ ssh user@octopi.local
  $ nano ~/.octoprint/config.yaml
]

[2. Make the appearance section look something like this. Note that you may have to add sections if they're not already there. Change the order as you like. You might be able to just add the plugin line under tab: to make it first. Experiment. Note the name to add: plugin_webcamtab]

appearance:
  components:
    order:
      tab:
        - temperature
        - plugin_webcamtab
        - gcodeviewer
        - terminal
        - timelapse
        - control

[3. Back in the OctoPrint interface, pick "Restart OctoPrint" from the power menu at the top. Then refresh the page as prompted.]

**Comment by malnvenshorn** [comment]
@nickm324 It does exactly what the description says - moving the webcam into it's own tab. Nothing more nothing less. The develop version is already compatible to the FullScreen plugin.

I'm closing this now because the problem seems solved.
