### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by HarkaranSinghBedi** [malnvenshorn/OctoPrint-WebcamTab#11]

**Comment by HarkaranSinghBedi** [comment]
Please update the plugin to work with Python 3 Octoprint instances.

**Comment by nforceroh** [comment]
As a workaround you can install manually and edit the necessary file
/home/pi/oprint/bin/python3 -m pip install "https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/master.zip"
change from /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/__init__.py
`__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"`
to
```
__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
__plugin_pythoncompat__ = ">=2.7,<4"
```


then restart octoprint

**Comment by HarkaranSinghBedi** [comment]
> As a workaround you can install manually and edit the necessary file
> /home/pi/oprint/bin/python3 -m pip install "https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/master.zip"
> change from /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/**init**.py
> `__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"`
> to
> 
> ```
> __copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
> __plugin_pythoncompat__ = ">=2.7,<4"
> ```
> 
> then restart octoprint

Thank you so much, this works 👍
