### ISSUE TITLE
Tab created but no webcam display in 1.5.0rc3

### ISSUE THREAD

**Issue by DodgeDeBoulet** [malnvenshorn/OctoPrint-WebcamTab#13]
As per subject. Tab displays, but when selecting it no video feed is presented, nor is a video-sized bounding box created. Just a thin, horizontal block.

**Comment by jneilliii** [comment]
If you want to try I just patched together a fix for webcamtab that seems to work in 1.5.0 with my limited testing. You can install by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install.

```
https://github.com/jneilliii/OctoPrint-WebcamTab/archive/master.zip
```

**Comment by DodgeDeBoulet** [comment]
Seems to be working fine for me now. Thanks for jumping on this!

**Comment by jneilliii** [comment]
It's probably not the best approach with the new webcam options in 1.5.0, but it does at least seem to work. Unfortunately, it's not a backwards compatible change.

**Comment by ajghor** [comment]
I had the same problem with the 1.5.0 release version. This fixed it. Thanks.

**Comment by markwinger** [comment]
I saw the same problem, and the fix worked for me too.

**Comment by smnino** [comment]
I have two separate machines and installations. The fix is not working on either install. The address for the stream works but is not displayed within the Octoprint web UI.

**Comment by gruvin** [comment]
Please see issue #14. My version supports python3 as well as OctoPrint v1.3, 1.4, 1.5. Please report any bugs via the issue tracker at https://github.com/gruvin/OctoPrint-WebcamTab

**Comment by readeral** [comment]
> It's probably not the best approach with the new webcam options in 1.5.0, but it does at least seem to work. Unfortunately, it's not a backwards compatible change.

Can you elaborate on why this isn't the best approach?

**Comment by jneilliii** [comment]
It might be, I just don't know for sure. It was a quick hack just to get the plugin to work again. But since then, @gruvin has adopted the plugin and maintaining it now on his fork.

**Comment by malnvenshorn** [comment]
Closing, because the plugin has been updated.
