### ISSUE TITLE
Author appears to have abandoned this project. Emails bounce.

### ISSUE THREAD

**Issue by gruvin** [malnvenshorn/OctoPrint-WebcamTab#14]
I'm in the process of publishing a replacement, which supports OctoPrint v1.3.5, 1.4.x and 1.5.x. Also python3.

Meanwhile, you can find it at https://github.com/gruvin/OctoPrint-WebcamTab/archive/0.2.0.zip

**Comment by DodgeDeBoulet** [comment]
Is the link you've provided a version that is supposed to work? Because it doesn't ... I get the exact same results as I reported in [Tab created but no webcam display in 1.5.0rc3 #13](https://github.com/malnvenshorn/OctoPrint-WebcamTab/issues/13). 

[This version does work, however](https://github.com/jneilliii/OctoPrint-WebcamTab/archive/master.zip), provided in the linked issue by [jneilliii](https://github.com/jneilliii).

**Comment by gruvin** [comment]
@DodgeDeBoulet Thanks fior the feedback. Yes, it should. Did you remove the old/original plugin?

We should move this discussion to https://github.com/gruvin/OctoPrint-WebcamTab/issues/1

Meanwhile, I installed mine directly from the repo. I'll download that auto-generated master.zip and try it out. Strange.

**Comment by gruvin** [comment]
> Is the link you've provided a version that is supposed to work? Because it doesn't ...

Try this one: https://github.com/gruvin/OctoPrint-WebcamTab/archive/0.2.0.zip

I was using a different plugin identifier previously, meaning that both "...WebcamTab" and "...WebcamTab G" would end up installed (and conflicting) unless you manually deleted the other. This one -- almost a complete rewrite since then -- should "upgrade" any previously installed version. However, you'll now need to remove the "G" version if it's still there.

Please report bugs at https://github.com/gruvin/OctoPrint-WebcamTab/issues

**Comment by DodgeDeBoulet** [comment]
The URL you supplied appears to be invalid; I get a 404 attempting to
download it via the browser, and that appears to cause the plugin manager
to hang (which probably should be reported as a plugin manager bug).

I went to your repository and was able to install the 0.2.0 release
version, however, and that appears to be working fine. Thanks!

**Comment by gruvin** [comment]
@DodgeDeBoulet thanks for the feedback. Glad 0.2.0 is now working for you. 👍 

fwiw, I was having weird issues with git last night. I had to manually rebase and force push at some point to fix it all. That invalidated the release tags for a short time, until I fixed them (10 mins?). You must have hit the link right in that narrow window. Murphy. ;-)
