### ISSUE TITLE
Blank tab

### ISSUE THREAD

**Issue by SageCrispin** [malnvenshorn/OctoPrint-WebcamTab#15]
Not working with 1.5.1. Worked good until now.

**Comment by jbuszkie** [comment]
You can use @gruvin 's fork.  I uninstalled this version and then used his version using the manual URL.  https://github.com/gruvin/OctoPrint-WebcamTab/archive/master.zip

Thanks to him for picking this up!

**Comment by bmfkai** [comment]
Sweet, came here looking for exactly this.  Also appears to simply overwrite the old one so no need to disable/uninstall the plugin, just install the new one and restart.

**Comment by SimonTelescopium** [comment]
Thanks @jbuszkie I used @gruvin 's fork and it worked :-)

**Comment by Fatmax1982** [comment]
> You can use @gruvin 's fork. I uninstalled this version and then used his version using the manual URL. https://github.com/gruvin/OctoPrint-WebcamTab/archive/master.zip
> 
> Thanks to him for picking this up!

Link doesn't work.
Any alternative?

**Comment by jbuszkie** [comment]
Link seems to work fine for me still?

**Comment by malnvenshorn** [comment]
Closing, because the plugin has been updated.
