### ISSUE TITLE
Tool shows 0c

### ISSUE THREAD

**Issue by ironicbadger** [malnvenshorn/OctoPrint-WebcamTab#2]
On the nightly dated 20/03/18 on a brand new Pi 3 B+ (hence the nightly) the tool temp shows as 0C in fullscreen view. Bed temp reads correctly.

**Comment by malnvenshorn** [comment]
This has nothing to do with the WebcamTab plugin. You should take a look at the issue tracker of the corresponding FullscreenPlugin. https://github.com/BillyBlaze/OctoPrint-FullScreen/issues/9
