### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by jneilliii** [malnvenshorn/OctoPrint-WebcamTab#6]
**Is your feature request related to a problem? Please describe.**
Running the latest version of OctoPrint 1.4.0 in a Python 3 environment does not allow for the use of this plugin as it is detected as incompatible.

**Describe the solution you'd like**
The ability to run the plugin in a Python 3 environment.

**Additional context**
Please see [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html) for additional information regarding OctoPrint and Python 3 Migration/Integration.

**Comment by nforceroh** [comment]
As a workaround you can install manually and edit the necessary file
/home/pi/oprint/bin/python3 -m pip install "https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/master.zip"
change from /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/init.py
__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
to

__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
__plugin_pythoncompat__ = ">=2.7,<4"
then restart octoprint

**Comment by nforceroh** [comment]
As a workaround you can install manually and edit the necessary file
/home/pi/oprint/bin/python3 -m pip install "https://github.com/malnvenshorn/OctoPrint-WebcamTab/archive/master.zip"
change from `/home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamtab/__init__.py`
```
__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
```
to
```
__copyright__ = "Copyright (C) 2017 Sven Lohrmann - Released under terms of the AGPLv3 License"
__plugin_pythoncompat__ = ">=2.7,<4"
```
then restart octoprint

**Comment by jneilliii** [comment]
or install the patched fork, which has also been submitted as a PR to the plugin, using this URL...

https://github.com/7FM/OctoPrint-WebcamTab/archive/patch-1.zip

**Comment by gruvin** [comment]
Please see issue #14. My version supports python3 as well as OctoPrint v1.3, 1.4, 1.5. Please report any bugs via the issue tracker at https://github.com/gruvin/OctoPrint-WebcamTab

**Comment by malnvenshorn** [comment]
Closing, because the plugin has been updated.
